ln -s $HOME/.config/dotfiles/i3/config $HOME/.config/i3/config
ln -s $HOME/.config/dotfiles/compton.conf $HOME/.config/compton.conf
ln -s $HOME/.config/dotfiles/.gtkrc-2.0 $HOME/.gtkrc-2.0
ln -s $HOME/.config/dotfiles/.gtkrc-2.0.mine $HOME/.gtkrc-2.0.mine
ln -s $HOME/.config/dotfiles/.i3blocks.conf $HOME/.i3blocks.conf
ln -s $HOME/.config/dotfiles/redshift.conf $HOME/.config/redshift.conf
ln -s $HOME/.config/dotfiles/.vimperatorrc $HOME/.vimperatorrc
ln -s $HOME/.config/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/.config/dotfiles/.Xdefaults $HOME/.Xdefaults
ln -s $HOME/.config/dotfiles/.Xresources $HOME/.Xresources
ln -s $HOME/.config/dotfiles/.xprofile $HOME/.xprofile
ln -s $HOME/.config/dotfiles/.zshrc $HOME/.zshrc
